-- Reference definition for the shared operational history.
-- These objects already exist after the first pipeline adoption. Do not execute
-- CREATE OR REPLACE VIEW during each repository rollout without shared approval.

CREATE TABLE IF NOT EXISTS PRD_MDP.MDP_STG.PIPELINE_RUNS (
    RUN_ID                  VARCHAR         NOT NULL,
    PIPELINE_NAME           VARCHAR         NOT NULL,
    PIPELINE_VERSION        VARCHAR,
    ENVIRONMENT             VARCHAR         NOT NULL,
    STATUS                  VARCHAR         NOT NULL,
    DATABRICKS_JOB_ID       VARCHAR,
    DATABRICKS_JOB_RUN_ID   VARCHAR,
    DATABRICKS_TASK_RUN_ID  VARCHAR,
    DATABRICKS_TASK_NAME    VARCHAR,
    ATTEMPT_NUMBER          NUMBER,
    TRIGGER_TYPE            VARCHAR,
    SOURCE_NAME             VARCHAR,
    SOURCE_FILE             VARCHAR,
    TARGET_NAME             VARCHAR,
    PERIOD_START_DATE       DATE,
    PERIOD_END_DATE         DATE,
    STARTED_AT_UTC          TIMESTAMP_TZ    NOT NULL,
    COMPLETED_AT_UTC        TIMESTAMP_TZ    NOT NULL,
    DURATION_SECONDS        NUMBER(18, 3)   NOT NULL,
    SOURCE_ROWS             NUMBER,
    STAGING_ROWS            NUMBER,
    TRANSFORMED_ROWS        NUMBER,
    TARGET_ROWS_BEFORE      NUMBER,
    TARGET_ROWS_AFTER       NUMBER,
    TARGET_ROW_DELTA        NUMBER,
    BUSINESS_METRICS_JSON   VARCHAR,
    ERROR_TYPE              VARCHAR,
    ERROR_MESSAGE           VARCHAR,
    CREATED_AT_UTC          TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Append-only execution history shared by enterprise data pipelines';

CREATE OR REPLACE VIEW PRD_MDP.MDP_STG.VW_PIPELINE_RUNS AS
SELECT
    RUN_ID,
    PIPELINE_NAME,
    PIPELINE_VERSION,
    ENVIRONMENT,
    STATUS,
    DATABRICKS_JOB_ID,
    DATABRICKS_JOB_RUN_ID,
    DATABRICKS_TASK_RUN_ID,
    DATABRICKS_TASK_NAME,
    ATTEMPT_NUMBER,
    TRIGGER_TYPE,
    SOURCE_NAME,
    SOURCE_FILE,
    TARGET_NAME,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    STARTED_AT_UTC,
    COMPLETED_AT_UTC,
    DURATION_SECONDS,
    SOURCE_ROWS,
    STAGING_ROWS,
    TRANSFORMED_ROWS,
    TARGET_ROWS_BEFORE,
    TARGET_ROWS_AFTER,
    TARGET_ROW_DELTA,
    TRY_PARSE_JSON(BUSINESS_METRICS_JSON) AS BUSINESS_METRICS,
    ERROR_TYPE,
    ERROR_MESSAGE,
    CREATED_AT_UTC
FROM PRD_MDP.MDP_STG.PIPELINE_RUNS;

CREATE OR REPLACE VIEW PRD_MDP.MDP_STG.VW_PIPELINE_DAILY_PERFORMANCE AS
SELECT
    PIPELINE_NAME,
    CAST(STARTED_AT_UTC AS DATE) AS RUN_DATE_UTC,
    COUNT(*) AS TOTAL_ATTEMPTS,
    COUNT_IF(STATUS = 'SUCCEEDED') AS SUCCEEDED_ATTEMPTS,
    COUNT_IF(STATUS = 'FAILED') AS FAILED_ATTEMPTS,
    COUNT_IF(STATUS = 'SKIPPED') AS SKIPPED_ATTEMPTS,
    ROUND(
        100 * COUNT_IF(STATUS = 'SUCCEEDED')
        / NULLIF(COUNT_IF(STATUS IN ('SUCCEEDED', 'FAILED')), 0),
        2
    ) AS SUCCESS_RATE_PERCENT,
    AVG(DURATION_SECONDS) AS AVG_DURATION_SECONDS,
    MEDIAN(DURATION_SECONDS) AS MEDIAN_DURATION_SECONDS,
    MIN(DURATION_SECONDS) AS MIN_DURATION_SECONDS,
    MAX(DURATION_SECONDS) AS MAX_DURATION_SECONDS,
    SUM(SOURCE_ROWS) AS TOTAL_SOURCE_ROWS,
    SUM(TARGET_ROWS_AFTER) AS TOTAL_TARGET_ROWS_AFTER
FROM PRD_MDP.MDP_STG.PIPELINE_RUNS
GROUP BY PIPELINE_NAME, CAST(STARTED_AT_UTC AS DATE);
